version: '3'

services: 
  chatbot_app:
    container_name: chatbot_app
    restart: always
    build: ./chatbot_app
    ports:
      - "3978:3978"
    command: gunicorn app:chatbot --bind 0.0.0.0:3978 --worker-class aiohttp.GunicornWebWorker
 
